"use client";
import {useEffect,useState} from "react"; import {getState,saveState,seedCategories,Task,User} from "../lib/storage";
type Page="home"|"tasks"|"earnings"|"transactions"|"withdraw"|"profile"|"settings"|"support"|"admin";
export default function App(){
 const [s,setS]=useState<any>(null); const [user,setUser]=useState<User|null>(null); const [page,setPage]=useState<Page>("home"); const [open,setOpen]=useState(false); const [selected,setSelected]=useState<Task|null>(null); const [msg,setMsg]=useState("");
 useEffect(()=>{const st=getState();setS(st);const u=sessionStorage.getItem("ss_user");if(u)setUser(JSON.parse(u))},[]);
 if(!s)return <div className="content">Loading SkillSpace…</div>;
 const go=(p:Page)=>{setPage(p);setSelected(null);setOpen(false);setMsg("")};
 const login=(name:string,email:string,role:"worker"|"admin"="worker")=>{const u={name,email,role};sessionStorage.setItem("ss_user",JSON.stringify(u));setUser(u)};
 if(!user)return <Auth onLogin={login}/>;
 const submit=(t:Task)=>{if(s.submitted.includes(t.id)){setMsg("You have already submitted this task.");return} if(s.submitted.length>=s.unlocked){setMsg("Complete the current batch and unlock the next 5 tasks.");return} s.submitted.push(t.id);s.balance+=t.reward;s.transactions.unshift({type:"Task reward",amount:t.reward,date:new Date().toLocaleString()});saveState(s);setS({...s});setMsg("Task submitted successfully. Reward added to Earnings.");};
 return <div className="shell">{open&&<><div className="overlay" onClick={()=>setOpen(false)}/><Drawer s={s} user={user} go={go} close={()=>setOpen(false)}/></>}
 <header className="topbar"><button className="menuBtn" onClick={()=>setOpen(true)}>☰ Menu</button><div className="brand">SKILLSPACE</div><div className="welcome">Welcome back, <b>{user.name}</b></div></header>
 <main className="content">{page==="home"&&<Home s={s} go={go}/>}
 {page==="tasks"&&<Tasks s={s} selected={selected} setSelected={setSelected} submit={submit} msg={msg}/>}
 {page==="earnings"&&<Money title="Earnings" amount={s.balance} transactions={s.transactions}/>}
 {page==="transactions"&&<Transactions items={s.transactions}/>}
 {page==="withdraw"&&<Withdraw s={s} setS={setS} msg={msg} setMsg={setMsg}/>}
 {page==="profile"&&<Profile user={user}/>} {page==="settings"&&<Settings/>}
 {page==="support"&&<Support s={s}/>} {page==="admin"&&user.role==="admin"&&<Admin s={s} setS={setS}/>}</main><footer className="footer">Need help? {s.supportEmail} · WhatsApp {s.supportWhatsApp}</footer></div>
}
function Auth({onLogin}:{onLogin:(n:string,e:string,r?:"worker"|"admin")=>void}){const[n,setN]=useState("");const[e,setE]=useState("");const[r,setR]=useState<"worker"|"admin">("worker");return <div className="form"><div className="brand">SKILLSPACE</div><h1>Welcome</h1><p className="muted">Connect with clients and access available online work.</p><input className="field" placeholder="Full name" value={n} onChange={x=>setN(x.target.value)}/><input className="field" placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/><select className="field" value={r} onChange={x=>setR(x.target.value as any)}><option value="worker">Worker</option><option value="admin">Admin demo</option></select><button className="btn primary" onClick={()=>n&&e&&onLogin(n,e,r)}>Log in / Sign up</button></div>}
function Drawer({s,user,go,close}:{s:any,user:User,go:(p:Page)=>void,close:()=>void}){return <><aside className="drawer"><div className="drawerHead"><b>Menu</b><button className="btn ghost" onClick={close}>×</button></div><div className="balance"><small>Available balance</small><div className="money">${s.balance.toFixed(2)}</div><small>KSh {(s.balance*130).toFixed(0)}</small></div><div className="nav">{([["home","Home / Dashboard"],["tasks","Tasks"],["earnings","Earnings"],["transactions","Transactions"],["withdraw","Withdraw"],["profile","Profile"],["settings","Settings"],["support","Support"]] as any[]).map(([p,l])=><button key={p} onClick={()=>go(p)}>{l}</button>)}{user.role==="admin"&&<button onClick={()=>go("admin")}>Admin</button>}<button onClick={()=>{sessionStorage.removeItem("ss_user");location.reload()}}>Log Out</button></div></aside></>}
function Home({s,go}:{s:any,go:(p:Page)=>void}){return <><div className="hero"><h1>Work, earn and grow with SkillSpace.</h1><p>Find available tasks, complete quality work and track your earnings.</p></div><div className="grid"><div className="card"><h3>Available Tasks</h3><div className="money">{s.tasks.length-s.submitted.length}</div><button className="btn primary" onClick={()=>go("tasks")}>Browse Tasks</button></div><div className="card"><h3>Earnings</h3><div className="money">${s.balance.toFixed(2)}</div><p className="muted">KSh {(s.balance*130).toFixed(0)}</p></div><div className="card"><h3>Next unlock</h3><p>First 5 tasks are free. After each batch of 5, pay $2 (KSh 260) to unlock the next batch.</p></div></div><div className="section"><h2>Task categories</h2><div className="grid">{seedCategories.map(c=><div className="card" key={c}><span className="pill">{c}</span><p className="muted">Available work in {c}.</p><button className="btn primary" onClick={()=>go("tasks")}>View Tasks</button></div>)}</div></div></>}
function Tasks({s,selected,setSelected,submit,msg}:{s:any,selected:Task|null,setSelected:(t:Task|null)=>void,submit:(t:Task)=>void,msg:string}){if(selected)return <div><button className="back" onClick={()=>setSelected(null)}>← Back to tasks</button><div className="card"><span className="pill">{selected.category}</span><h1>{selected.title}</h1><p>{selected.description}</p><b>${selected.reward.toFixed(2)} · KSh {(selected.reward*130).toFixed(0)}</b><div style={{marginTop:18}}><button className="btn green" onClick={()=>submit(selected)}>Submit Task</button></div>{msg&&<div className="notice success">{msg}</div>}</div></div>;return <div><h1>Available Tasks</h1><p className="muted">Choose a task and open its details before submitting.</p>{msg&&<div className="notice">{msg}</div>}{seedCategories.map(c=><div className="section" key={c}><h2>{c}</h2><div className="taskrow">{s.tasks.filter((t:Task)=>t.category===c).map((t:Task)=><div className="card task" key={t.id}><span className="pill">{t.category}</span><h3>{t.title}</h3><p className="muted">{t.description}</p><b>${t.reward.toFixed(2)} · KSh {(t.reward*130).toFixed(0)}</b><br/><button className="btn primary" style={{marginTop:12}} onClick={()=>setSelected(t)}>View Task</button></div>)}</div></div>)}</div>}
function Money({title,amount,transactions}:{title:string,amount:number,transactions:any[]}){return <><h1>{title}</h1><div className="card"><div className="money">${amount.toFixed(2)}</div><p>KSh {(amount*130).toFixed(0)}</p></div><div className="section"><h2>Recent earnings</h2><Transactions items={transactions}/></div></>}
function Transactions({items}:{items:any[]}){return <div className="card">{items.length?items.map((x,i)=><div key={i} style={{padding:"12px 0",borderBottom:"1px solid #eee"}}><b>{x.type}</b><span style={{float:"right"}}>${Number(x.amount).toFixed(2)}</span><div className="muted">{x.date}</div></div>):<p className="muted">No transactions yet.</p>}</div>}
function Withdraw({s,setS,msg,setMsg}:{s:any,setS:(x:any)=>void,msg:string,setMsg:(x:string)=>void}){const[amt,setAmt]=useState("");const a=Number(amt);return <><h1>Withdraw</h1><div className="card"><p>Minimum withdrawal: <b>$100 · KSh 13,000</b></p><input className="field" type="number" placeholder="Amount in USD" value={amt} onChange={e=>setAmt(e.target.value)}/><button className="btn primary" onClick={()=>{if(a<100){setMsg("Minimum withdrawal is $100 (KSh 13,000).");return}if(a>s.balance){setMsg("Insufficient balance.");return}s.balance-=a;s.transactions.unshift({type:"Withdrawal request",amount:-a,date:new Date().toLocaleString()});saveState(s);setS({...s});setMsg("Withdrawal request submitted.");}}>Request Withdrawal</button>{msg&&<div className="notice">{msg}</div>}</div></>}
function Profile({user}:{user:User}){return <><h1>Profile</h1><div className="card"><p><b>Name</b><br/>{user.name}</p><p><b>Email</b><br/>{user.email}</p></div></>}
function Settings(){return <><h1>Settings</h1><div className="card"><h3>Account settings</h3><p className="muted">Your account preferences are managed here.</p></div></>}
function Support({s}:{s:any}){return <><h1>Support</h1><div className="card"><h3>Need help?</h3><p>Email: {s.supportEmail}</p><p>WhatsApp: {s.supportWhatsApp}</p></div></>}
function Admin({s,setS}:{s:any,setS:(x:any)=>void}){const[t,setT]=useState({category:seedCategories[0],title:"",description:"",reward:"2"});const[c,setC]=useState(s.supportEmail);const[w,setW]=useState(s.supportWhatsApp);return <><h1>Admin</h1><div className="card"><h2>Add task</h2><select className="field" value={t.category} onChange={e=>setT({...t,category:e.target.value})}>{seedCategories.map(x=><option key={x}>{x}</option>)}</select><input className="field" placeholder="Task title" value={t.title} onChange={e=>setT({...t,title:e.target.value})}/><textarea className="field" placeholder="Description" value={t.description} onChange={e=>setT({...t,description:e.target.value})}/><input className="field" type="number" placeholder="Reward USD" value={t.reward} onChange={e=>setT({...t,reward:e.target.value})}/><button className="btn primary" onClick={()=>{if(!t.title)return;const nt={...t,id:Date.now(),reward:Number(t.reward)};s.tasks.push(nt);saveState(s);setS({...s});setT({...t,title:"",description:""})}}>Add Task</button></div><div className="card section"><h2>Edit support contacts</h2><input className="field" value={c} onChange={e=>setC(e.target.value)}/><input className="field" value={w} onChange={e=>setW(e.target.value)}/><button className="btn primary" onClick={()=>{s.supportEmail=c;s.supportWhatsApp=w;saveState(s);setS({...s})}}>Save Contacts</button></div></>}
