"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
export default function Support(){
 const [email,setEmail]=useState("skillspace@gmail.com"); const [whatsapp,setWhatsapp]=useState("0752372102");
 useEffect(()=>{(async()=>{const {data}=await supabase.from("settings").select("support_email,support_whatsapp").limit(1).maybeSingle(); if(data){if(data.support_email)setEmail(data.support_email);if(data.support_whatsapp)setWhatsapp(data.support_whatsapp)}})()},[]);
 const digits=whatsapp.replace(/\D/g,""); const waNumber=digits.startsWith("0")?`254${digits.slice(1)}`:digits;
 return <div className="shell"><aside className="sidebar"><div className="brand">Skill<span>Space</span></div><nav className="nav"><Link href="/">🏠 <span>Dashboard</span></Link><Link href="/tasks">📋 <span>Find Tasks</span></Link><Link href="/earnings">💰 <span>Earnings</span></Link><Link href="/wallet">👛 <span>Wallet</span></Link><Link className="active" href="/support">💬 <span>Support</span></Link></nav></aside><main className="main"><header className="topbar"><div className="crumb">Support & Contact</div><div className="avatar">SS</div></header><div className="content"><div className="hero"><div><div className="eyebrow">We're here to help</div><h1>Support & Contact</h1><p>Reach the SkillSpace support team whenever you need help.</p></div></div><div className="two"><div className="card"><h2 style={{marginBottom:16}}>Contact us</h2><div className="notice">Email<br/><a href={`mailto:${email}`} style={{color:"#80aaff"}}>{email}</a></div><div className="notice">WhatsApp<br/><a href={`https://wa.me/${waNumber}`} style={{color:"#62e39e"}}>{whatsapp}</a></div></div><div className="card"><h2 style={{marginBottom:16}}>Quick help</h2><p style={{fontSize:12,color:"#91a3bd",lineHeight:1.7}}>Questions about tasks, account access, earnings or withdrawals? Contact support and include your account email and task reference when available.</p></div></div></div></main></div>}
